// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP4kfs3kU4MXTK2yIwlZK12Y7vqRMw6Vk',
    appId: '1:149925493604:web:a47404e871d20167f99871',
    messagingSenderId: '149925493604',
    projectId: 'storeapp-91bad',
    authDomain: 'storeapp-91bad.firebaseapp.com',
    storageBucket: 'storeapp-91bad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJV5AYC7cIgXqtIHt1ZzDOA-eDAnmTnLY',
    appId: '1:149925493604:android:204e7c7fc742b9d4f99871',
    messagingSenderId: '149925493604',
    projectId: 'storeapp-91bad',
    storageBucket: 'storeapp-91bad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuco98bg3Vh38eVPzGV3NXteNG44Noj7I',
    appId: '1:149925493604:ios:6ed4cb9558cb8e34f99871',
    messagingSenderId: '149925493604',
    projectId: 'storeapp-91bad',
    storageBucket: 'storeapp-91bad.appspot.com',
    iosClientId: '149925493604-fmf47qh7dnvcq0qlvj6mcuabah32t0a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuco98bg3Vh38eVPzGV3NXteNG44Noj7I',
    appId: '1:149925493604:ios:870e18ecb3505924f99871',
    messagingSenderId: '149925493604',
    projectId: 'storeapp-91bad',
    storageBucket: 'storeapp-91bad.appspot.com',
    iosClientId: '149925493604-o2t5c817grsdgg5cvaerd5cg5p44s1eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp.RunnerTests',
  );
}
